

SOCKS_VERSION = 5


class SocksReply:

    SUCCESS = 0x00
    GENERAL_SOCKS_SERVER_FAILURE = 0x01
    CONNECTION_NOT_ALLOWED_BY_RULESET = 0x02
    NETWORK_UNREACHABLE = 0x03
    HOST_UNREACHABLE = 0x04
    CONNECTION_REFUSED = 0x05
    TTL_EXPIRED = 0x06
    ADDRESS_TYPE_NOT_SUPPORTED = 0x07
    COMMAND_NOT_SUPPORTED = 0x07
